### ISSUE TITLE
Email to the attendees

### ISSUE THREAD

**Issue by dlstrong** [data-carpentry-for-agriculture/trial-lesson#12]
Items to include
* Confirmation of the dates they'll be attending
* To-bring information
* Encouragement to pre-install, notes that we'll have USB sticks available if they can't

Email text draft at: https://uofi.box.com/s/foyiuy0e50qxplmml9hxcpyowek3un0s

**Comment by jnaiman** [comment]
I guess we should wait until we have install instructions?

Also, should we set up any online "let us help you install things" times before the workshop?

Also also, do we want to do any installation help sessions the night before (I can't make because I teach), or the hour before the workshop starts?

**Comment by dlstrong** [comment]
a) Yep, we definitely need install instructions ready to go before we send.
b and c) That would be super awesome if we can, but I don't know enough about how to fix a botched install to be able to help.
d) "The hour before the workshop starts" can't possibly be enough time. On a brand new high powered gaming machine, it still took 3.5 hours to get through just the R and R Studio and package installs, with no errors or restarts, and without even starting on QGIS.

**Comment by jnaiman** [comment]
Also, link to the pre-workshop survey (edit link): https://docs.google.com/forms/d/1oCz3wc3bJ3z5h5Pj_pMYQXsTOefua622ntrymqGvnKg/edit?usp=sharing

**Comment by dlstrong** [comment]
I believe Lisa sent this yesterday?
