### ISSUE TITLE
Write up a quick "How to install packages before the workshop"

### ISSUE THREAD

**Issue by jnaiman** [data-carpentry-for-agriculture/trial-lesson#13]
We need to have them try to install things before the workshop.

- [x] Figure out what packages need to be installed and figure out how long it can take for these packages to install so folks don't panic (Jill has small list, Brittani needs to double check it, Dena can tell us length of install time)
- [x] Write an install script that does the installation *and* has some examples/runs checks to see if everything installs ok (Jill/Brittani can do this)
- [x] Write up installation instructions using this script with screen shots for both Mac & Windows machines (Jill can do Mac, Windows anybody?)
- [x] Have a "how to get help" if something goes wrong -- online "office hours"?  Via email? (Brittani? Dena? Jill?)

**Comment by dlstrong** [comment]
I'm not the best person to help debug an install given the trouble I had getting things to install on my own laptop. I can do Windows screen shots, though.

**Comment by dlstrong** [comment]
Also, how much of this will the USB stick mitigate, @jnaiman ? That might help reduce the need for "before the event" troubleshooting, if we can get a USB stick based run method functional enough.

**Comment by jnaiman** [comment]
So, I've never used R from a USB stick before @dlstrong -- but maybe everything will work perfectly? :)

Also, does this mean we are going to give them USB sticks to take home so they can do things at home afterwards?

**Comment by dlstrong** [comment]
From the Slack chat - we have no chance that everyone will get everything preinstalled correctly before arriving, and we don't want to lose 3 hours to installation the way I did, and not everyone will have a less than a year old 64 bit Windows 10 computer with 16 Gb RAM and a 500 GB hard drive so mine was close to the theoretical best case scenario. So in that world, our fallback options look like some combination of loaner laptops and USB sticks.

Right now I don't yet know if I can make a USB stick that works Win10 64 to Win10 64, let alone the other variations, but I'm walking along the path of trying to get there.

So the current scenario looks like:
1) Encourage people to preinstall on their own computers
2) For those who do bring computers but don't preinstall, have USBs available (ideally pre-tested, which I'm hoping to do this afternoon)
3) For those whose computers can't handle it or who don't bring computers, have loaner computers available
...so that hopefully there's no way we can lose more than an hour to initial setup and no one can be left behind.

I'm trying for belt, suspenders, and duct tape here...

**Comment by lvclark** [comment]
If it hasn't been done yet, I also recommend seeing if all of the packages
listed in the library commands really get used in the scripts/lessons.  You
can look at the help page for a function to see what package it is from.
If a package looks like it might not be needed, comment out the library
command and see if the Rmd will compile.

**Comment by dlstrong** [comment]
Current status as of 3 pm: In the middle of copying the Windows package dependencies to the Box folder, which is going to take about another 45 minutes if I'm lucky (there have been several interrupted starts). After that I need to try it from the USB stick and see if it's possible to get the packages connected on the USB installation, and then I need to see if that will run on Windows 7.

**Comment by dlstrong** [comment]
USB stick update: Proof of concept approved across 2 Windows 10 machines and 2 drive letters. It's apparently important to put ggplot2 in the library last instead of first; I'll update the setup script to reflect that. People using the stick SHOULD NOT run the install part of the script, just the library part of the script, so I think I'll separate those out into different files as well.

ETA, R and R Studio both work on Win 7 and on other drive letters as well. QGIS creates an env file that has pointers to the D drive which was the drive's letter assigned by the machine I did the install on. More testing later on whether updating that env file will let it work both on other machines and on Win 7, but too tired tonight.

**Comment by dlstrong** [comment]
I think we've got strategies for covering these set.
